### ISSUE TITLE
Databases 

### ISSUE THREAD

**Issue by Hello405p** [EpicEricEE/JustMoney#32]
Is it support database.

**Comment by EpicEricEE** [comment]
It supports SQLite and MySQL databases. You can choose in the config file:
```yml
# How the balance data is stored.
# Valid values are "flatfile", "sqlite" and "mysql".
storage-type: flatfile

# Where to reach your MySQL server
mysql:
  hostname: ""
  port: 3306
  database: ""
  username: ""
  password: ""
```
